### PR TITLE
Allow subscribing to association columns

### LINKED ISSUE #6: Listening for events based on extras
Hey! Super cool library. Would be awesome if I could subscribe beyond just an id, but specifically to the extra information. I.e. if you are viewing a post, you could:

```
# setup 
{EctoWatch, watchers: [{MyApp.Blog.Comment, :interted, extra_columns: [:post_id]}]}

# client
EctoWatch.subscribe(MyApp.Blog.Comment, :inserted, nil/true/:all, post_id)
```

For my use cases it would cut down on a ton of messages sent.

PS: completely aside, would be super neat if there was a debounce parameter... I saw mentions about config for triggers so just thought I'd drop that one in while I'm here :)

### PR DESCRIPTION
**Pull request by cheerfulstoic**
Fixes #6

Discussion here: https://github.com/cheerfulstoic/ecto_watch/discussions/7

Need to update the `README` with these changes 😅 

I'm definitely not happy with this code 😅   But it's pretty well tested and so it seems to work for now.  I'm planning on switching messages to three-element tuples instead of four-element tuples (see [this discussion](https://github.com/cheerfulstoic/ecto_watch/discussions/8)) and that will be a good opportunity to clean things up

### CODE REVIEW

**Comment by cheerfulstoic** [comment]
Hey @barrelltech

I finally got an implementation for #6.  I feel pretty good about the tests and I would normally release it on Hex, but I'm going to be offline for a bit, so I'll wait until I'm back.  In the meantime maybe you'd like to try pointing to this branch in your `mix.exs`?

**Comment by cheerfulstoic** [comment]
To make it easier to try out I've released a `0.6.0-rc1` version

**Comment by cheerfulstoic** [comment]
You might also want to check out rc2 which includes the changes in this PR: #12

**Comment by barrelltech** [comment]
Awesome! Just saw this now and downloaded it, but I won't get to it until tomorrow. Had to get things deployed before I got too far behind 😂

**Comment by cheerfulstoic** [comment]
I just released 0.6.0 as a non-RC version to support this 🎉

**Pull request merged**
